# Generated by Django 2.1.4 on 2018-12-21 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Item title?', max_length=30)),
                ('type', models.CharField(choices=[('Transportation', 'Transportation'), ('Food', 'Food'), ('Alcohol', 'Alcohol'), ('Cigarettes', 'Cigarettes'), ('Electronics', 'Electronics'), ('Leisure', 'Leisure'), ('Travelling', 'Travelling')], default='Transportation', max_length=14)),
                ('amount', models.IntegerField()),
                ('location', models.CharField(default='Item Locale?', max_length=30)),
                ('image', models.FileField(upload_to='uploads/')),
                ('comments', models.TextField(default='...')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
